server:
  port: 8080
spring:
  datasource:
    # H2 in memory database
    url:    jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    platform: h2
    # hikari
    type: com.zaxxer.hikari.HikariDataSource
    # see HikariConfigMXBean
    hikari:
      connection-timeout: 1000
      idle-timeout: 1000
      # maximum size that the pool is allowed to reach
      maximum-pool-size: 2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      fail-on-empty-beans: false
      
# liquibase setup
liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.yaml